#!/usr/bin/env bash
# Auto-generated by CMake - DO NOT EDIT MANUALLY
# This script allows building without CMake installed

set -e
cd "$(dirname "$0")/c-diff-core"

echo "Building vscode_diff (standalone mode)..."
echo "Compiler: /usr/bin/cc"
echo "Platform: Linux"

# Compiler and flags from CMake configuration
CC="/usr/bin/cc"
CFLAGS=" -Wall -Wextra -O2 -DNDEBUG -Iinclude -Ivendor -fPIC"
LDFLAGS="-shared -lm"

# Detect platform for library extension
if [[ "$OSTYPE" == "darwin"* ]]; then
    LIB_EXT="dylib"
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    LIB_EXT="so"
else
    LIB_EXT="so"
fi

# Source files (including bundled utf8proc)
SOURCES="\
src/diff_api.c \
src/render_plan.c \
default_lines_diff_computer.c \
src/char_level.c \
src/line_level.c \
src/myers.c \
src/optimize.c \
src/sequence.c \
src/range_mapping.c \
src/string_hash_map.c \
src/utils.c \
src/print_utils.c \
src/utf8_utils.c \
vendor/utf8proc.c"

# Build
mkdir -p build
echo "Compiling..."
$CC $CFLAGS $LDFLAGS -o libvscode_diff.$LIB_EXT $SOURCES

echo "Installing to plugin root..."
cp libvscode_diff.$LIB_EXT ../libvscode_diff.$LIB_EXT

echo "✓ Build successful: libvscode_diff.$LIB_EXT"
cd ..
